kind: pipeline
type: docker
name: Win-64🤡
steps:
node:
  server: USA
clone:
  disable: true
steps:
- name: 拉取代码
  image: alpine
  volumes:
  - name: cache
    path: /dist
  commands:
  - apk update
  - apk add git bash
  - cd /dist
  - git clone https://github.com/20020314/v2milk
# 依赖
- name: 安装依赖
  image: node:16.17-alpine3.15
  volumes:
  - name: cache
    path: /dist
  commands:
  - cd /dist/v2milk
  - echo "安装完成"
# v2ray-core
- name: 更新v2ray-core
  image: alpine
  volumes:
  - name: cache
    path: /dist
  commands:
  - apk update
  - apk add git unzip bash wget
  - mkdir /dist/download
  - mkdir -p /dist/v2milk/APP/extra/v2ray-core/Windows
  - cd /dist/download
  - wget https://github.com/v2ray/v2ray-core/releases/download/v4.28.2/v2ray-windows-64.zip
  - unzip *.zip
  - mv /dist/download/v2ray-windows-64/geoip.dat /dist/v2milk/APP/extra/v2ray-core/Windows
  - mv /dist/download/v2ray-windows-64/geosite.dat /dist/v2milk/APP/extra/v2ray-core/Windows
  - mv /dist/download/v2ray-windows-64/v2ctl.exe /dist/v2milk/APP/extra/v2ray-core/Windows
  - mv /dist/download/v2ray-windows-64/v2ray.exe /dist/v2milk/APP/extra/v2ray-core/Windows

# 构建安装包
- name: 构建安装包
  image: node:14
  volumes:
  - name: cache
    path: /dist
  commands:
  - cd /dist/v2milk/APP
  - npm install
  - npm install -g electron-builder
  - npm run dist:win64
# mv
volumes:
- name: cache
  temp: {}
